//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObscureAddress.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ObscureAddress.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turks and Caicos Islands
        ///Austria
        ///Bolivia
        ///Malta
        ///Montenegro
        ///Saudi Arabia
        ///Cambodia
        ///Peru
        ///Congo
        ///Nigeria
        ///Nicaragua
        ///Italy
        ///Belgium
        ///United States of America
        ///Vanuatu
        ///Hungary
        ///South Georgia and the South Sandwich Islands
        ///Uganda
        ///Chile
        ///Christmas Island
        ///Afghanistan
        ///Guadeloupe
        ///Isle of Man
        ///Dominican Republic
        ///Bouvet Island (Bouvetoya)
        ///Guyana
        ///Syrian Arab Republic
        ///Eritrea
        ///Cyprus
        ///Western Sahara
        ///Andorra
        ///Cook Islands
        ///Jordan
        ///Uzbekistan
        ///Singapore
        ///Guinea-Bissau
        ///Fiji
        ///Mexico
        ///Mayotte
        ///Bermuda
        ///Alge [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountryNames {
            get {
                return ResourceManager.GetString("CountryNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emma
        ///Olivia
        ///Ava
        ///Isabella
        ///Sophia
        ///Mia
        ///Charlotte
        ///Amelia
        ///Evelyn
        ///Abigail
        ///Harper
        ///Emily
        ///Elizabeth
        ///Sofia
        ///Ella
        ///Madison
        ///Scarlett
        ///Victoria
        ///Aria
        ///Grace
        ///Chloe
        ///Camila
        ///Penelope
        ///Layla
        ///Lillian
        ///Nora
        ///Zoey
        ///Mila
        ///Aubrey
        ///Hannah
        ///Lily
        ///Addison
        ///Eleanor
        ///Natalie
        ///Luna
        ///Savannah
        ///Brooklyn
        ///Leah
        ///Zoe
        ///Stella
        ///Hazel
        ///Ellie
        ///Paisley
        ///Audrey
        ///Skylar
        ///Violet
        ///Claire
        ///Bella
        ///Aurora
        ///Lucy
        ///Anna
        ///Samantha
        ///Caroline
        ///Aaliyah
        ///Kinsley
        ///Allison
        ///Maya
        ///Sarah
        ///Madelyn
        ///Adeline
        ///Alexa
        ///Ariana
        ///Elena
        ///Gabriella
        ///Naomi
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FemaleNames {
            get {
                return ResourceManager.GetString("FemaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string IgnoreWords {
            get {
                return ResourceManager.GetString("IgnoreWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liam
        ///Noah
        ///William
        ///James
        ///Benjamin
        ///Mason
        ///Elijah
        ///Oliver
        ///Jacob
        ///Lucas
        ///Michael
        ///Alexander
        ///Ethan
        ///Avery
        ///Daniel
        ///Matthew
        ///Aiden
        ///Henry
        ///Joseph
        ///Jackson
        ///Samuel
        ///Sebastian
        ///David
        ///Wyatt
        ///Riley
        ///Jayden
        ///John
        ///Owen
        ///Luke
        ///Gabriel
        ///Anthony
        ///Isaac
        ///Grayson
        ///Jack
        ///Julian
        ///Levi
        ///Christopher
        ///Joshua
        ///Andrew
        ///Lincoln
        ///Mateo
        ///Jaxon
        ///Nathan
        ///Aaron
        ///Isaiah
        ///Thomas
        ///Charles
        ///Caleb
        ///Josiah
        ///Christian
        ///Hunter
        ///Eli
        ///Jonathan
        ///Connor
        ///Landon
        ///Adrian
        ///Asher
        ///Cameron
        ///Leo
        ///Theodore
        ///Jeremiah
        ///Hudson
        ///Robert
        ///Easton
        ///Nolan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MaleNames {
            get {
                return ResourceManager.GetString("MaleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Nouns {
            get {
                return ResourceManager.GetString("Nouns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acdc Lane
        ///Albert Coates Lane
        ///Albert Road Drive
        ///Albion Alley
        ///Alsop Lane
        ///Altson Lane
        ///Amphlett Lane
        ///Angel Lane
        ///Aquarium Drive
        ///Artemis Lane
        ///Athenaeum Place
        ///Austral Lane
        ///Balcombe Place
        ///Banana Alley
        ///Bank Place
        ///Baptist Place
        ///Barry Lane
        ///Beaney Lane
        ///Bell Place
        ///Belman Place
        ///Benjamin Lane
        ///Bennetts Lane
        ///Bligh Place
        ///Block Arcade
        ///Block Court
        ///Block Place
        ///Boathouse Drive
        ///Boulton Parade
        ///Bourke Ml Street
        ///Bowen Lane
        ///Brabham Lane
        ///Brien Lane
        ///Brights Place
        ///Briscoe Lane
        ///Brown Alley
        ///Bullens Lane        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StreetNames {
            get {
                return ResourceManager.GetString("StreetNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smith
        ///Jones
        ///Williams
        ///Brown
        ///Wilson
        ///Taylor
        ///Anderson
        ///Johnson
        ///White
        ///Thompson
        ///Lee
        ///Martin
        ///Thomas
        ///Walker
        ///Kelly
        ///Young
        ///Harris
        ///King
        ///Ryan
        ///Roberts
        ///Hall
        ///Evans
        ///Davis
        ///Wright
        ///Baker
        ///Campbell
        ///Edwards
        ///Clark
        ///Robinson
        ///McDonald
        ///Hill
        ///Scott
        ///Clarke
        ///Mitchell
        ///Stewart
        ///Moore
        ///Turner
        ///Miller
        ///Green
        ///Watson
        ///Bell
        ///Wood
        ///Cooper
        ///Murphy
        ///Jackson
        ///James
        ///Lewis
        ///Allen
        ///Bennett
        ///Robertson
        ///Collins
        ///Cook
        ///Murray
        ///Ward
        ///Phillips
        ///O&apos;Brien
        ///Nguyen
        ///Davies
        ///Hughes
        ///Morris
        ///Adams
        ///Johnston
        ///Parker
        ///Ross
        ///Gray
        ///Gra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Surnames {
            get {
                return ResourceManager.GetString("Surnames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sydney
        ///Melbourne
        ///Brisbane
        ///Perth
        ///Adelaide
        ///Gold Coast
        ///Cranbourne
        ///Canberra
        ///Newcastle
        ///Wollongong
        ///Geelong
        ///Hobart
        ///Townsville
        ///Ipswich
        ///Cairns
        ///Toowoomba
        ///Darwin
        ///Ballarat
        ///Bendigo
        ///Launceston
        ///Mackay
        ///Rockhampton
        ///Maitland
        ///Bunbury
        ///Coffs Harbour
        ///Bundaberg
        ///Wagga Wagga
        ///Hervey Bay
        ///Shepparton
        ///Albury
        ///Port Macquarie
        ///Pakenham
        ///Tamworth
        ///Caloundra
        ///Orange
        ///Dubbo
        ///Geraldton
        ///Nowra
        ///Bathurst
        ///Queanbeyan
        ///Frankston
        ///Sunbury
        ///Warrnambool
        ///Wodonga
        ///Albany
        ///Gladstone
        ///Mildura
        ///Southport
        ///Alice Springs
        ///Dand [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TownNames {
            get {
                return ResourceManager.GetString("TownNames", resourceCulture);
            }
        }
    }
}
